# Practice

In [2]:
# yesterday we studied about slicing & indexing in 2d matrices.
# today we will make it a little complex and use a combination of both slicing and indexing.

In [4]:
import numpy as np
t = np.arange(1,13).reshape((3,4))
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
# If I say fetch [[5,7],[9,11]]. we can do this with simple slicing.

t[1:,::2]

array([[ 5,  7],
       [ 9, 11]])

In [9]:
# try to fetch same elements using indices.

t[[1,1,2,2],[0,2,0,2]]

array([ 5,  7,  9, 11])

In [11]:
# now get [[5,7,8],[9,11,12]]. we have to combine slicing and indexing to fetch this.

t[1:,[0,2,3]] # OR t[1:,(0,2,3)]

array([[ 5,  7,  8],
       [ 9, 11, 12]])

In [14]:
t[1:,2] # if you write the index without square braces. it will give us answer in 1d array only.
# However if we pass square braces to it. it will return us a 2d array.

array([ 7, 11])

In [15]:
t[1:,[2]]

array([[ 7],
       [11]])

In [17]:
t[2,1::2]

array([10, 12])

In [18]:
t[[1,2],::-1]

array([[ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [19]:
t[[1,2],:-2:-2]

array([[ 8],
       [12]])

In [20]:
t[[1,2],-2::-2]

array([[ 7,  5],
       [11,  9]])

In [21]:
# quiz

m1 = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(m1[[0,2],0:2])

[[0 1]
 [8 9]]


In [22]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Masking

In [23]:
a = np.arange(1,13).reshape((3,4))
a<6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

###### 

In [25]:
a[a<6]

array([1, 2, 3, 4, 5])

In [28]:
a[(a<5) | (a>8)]


array([ 1,  2,  3,  4,  9, 10, 11, 12])

In [31]:
a = np.arange(2,14).reshape((3,4))
b = np.arange(1,13).reshape((3,4))

b%2==0

a[b%2==0]

array([ 3,  5,  7,  9, 11, 13])

# Universal Functions

In [35]:
a = np.arange(4)
np.sum(a)

6

In [37]:
a = np.arange(1,13).reshape(3,4)
a
np.sum(a)

78

In [38]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
# Let's say if I tell you to findout the sum of every row.

np.sum(a,axis=1)

array([10, 26, 42])

In [43]:
# now get the sum column wise.
np.sum(a,axis = 0)


array([15, 18, 21, 24])

In [44]:
np.min(a,axis=0)

array([1, 2, 3, 4])

In [46]:
np.max(a,axis=1)

array([ 4,  8, 12])

In [49]:
# using dtype in parameter because division in python always gives us a float value.
np.mean(a,axis=0,dtype='int')

array([5, 6, 7, 8])

In [50]:
np.sum(a,axis=-1)

array([10, 26, 42])

In [51]:
np.sum(a,axis=-2)

array([15, 18, 21, 24])

# Logical Operations any,all

In [52]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
a<b

array([ True,  True, False, False])

In [55]:
# It will check for atleast one true. Then it will return True else False.

np.any(a<b)


True

In [56]:
# It will check for all true values possible. then it will return True else False

np.all(a<b)

False

In [57]:
a = np.array([[1,2,3],[4,6,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.any(a>b))

True
