# Shallow copy VS Deep copy

In [2]:
import numpy as np

In [4]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [6]:
b = a.reshape((2,2))
b

array([[0, 1],
       [2, 3]])

In [7]:
a[0]=100
a

array([100,   1,   2,   3])

In [8]:
b

array([[100,   1],
       [  2,   3]])

In [9]:
# b here is nothing but a shallow copy of a
# This is how numpy array works internally. it will not create a seperate memory block for b . Both a and b are sharing the same memory space.
# It will just create a new header. And change values of the attributes of headers.
# Some attributes of headers (ndim,nshape,nsize,stride(stepsize) etc.).


In [10]:
# PROOF THEY ARE SHARING THE SAME MEMORY SPACE .

np.shares_memory(a,b)

True

In [12]:
# let's see some more examples.

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [19]:
c=a+2
print(c)
np.shares_memory(a,c)



[2 3 4 5 6]


False

In [15]:
# In this example it will create a seperate memory space. Because we performed an operation(+).The value of the element of c is totally different.
# And we have nothing in our headers. That fixes this.
# A seperate memory block is created whenever one tries to perform an operation.

In [16]:
d = a+0
d

array([0, 1, 2, 3, 4])

In [18]:

# In this example although we have same values. But we performed an operation.
# It doesn't matter if we are adding just 0 to it.It will create a different memory space

np.shares_memory(a,d)

False

In [20]:
# How to create a shallow copy in Numpy. we do it by using VIEW FUNCTION
view_a = a.view()

# Deep copy
### Deep copy means exact same copy but in a different memory location.

In [21]:
# How do I  create a proper deep copy in numpy.
# Two functions we will see (a).  .copy()  (b) copy.deepcopy()
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b = a.copy()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.shares_memory(a,b)

False

In [26]:
# One more example

a = np.array([[1,2,3],[4,5,6]])
print(a)

print('-'*100)

b = a.copy()
print(b)

[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]]


In [27]:
a[0,0]=100

a

array([[100,   2,   3],
       [  4,   5,   6]])

In [28]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.shares_memory(a,b)

False

In [30]:
# Hence this is a deep copy. Not sharing the same memory space
# But there is a problem here with .copy()
# we will see our problem with an example

In [34]:
c = np.array([1,'r',[1,2,3]],dtype='object')
c


array([1, 'r', list([1, 2, 3])], dtype=object)

In [35]:
d

array([1, 'r', list([1, 2, 3])], dtype=object)

In [36]:
# Now if I change the elements of C. d will be affected as well. Even after knowing the fact that we created a deep copy.
# This is because of an exception(object dtype). whenever we have object datatype deep copy will create a shallow copy only. 

In [50]:
c[2][0]=100
c

array([1, 'k', list([100, 2, 3])], dtype=object)

In [51]:
d

array([1, 'k', list([1, 2, 3])], dtype=object)

In [42]:
# To fix this and Always to be in safe side. We use copy.deepcopy(). Deepcopy will eliminate this.
# We have to import copy module first


In [43]:
import copy


In [44]:
c = np.array([1,'k',[1,2,3]],dtype='object')
c

array([1, 'k', list([1, 2, 3])], dtype=object)

In [45]:
d = copy.deepcopy(c)

In [46]:
d

array([1, 'k', list([1, 2, 3])], dtype=object)

In [47]:
c[2][0] = 100
c

array([1, 'k', list([100, 2, 3])], dtype=object)

In [48]:
d

array([1, 'k', list([1, 2, 3])], dtype=object)

In [53]:
np.shares_memory(c,d)

False

 # Expansion and Reduction

In [55]:
a = np.arange(9)
a.shape

(9,)

In [56]:
b = a.reshape((3,3))
b.shape

(3, 3)

In [57]:
# we expanded our dimension, earlier it was 1d now it is 2d.

In [59]:
c = a.reshape((3,3,1))
c
# Now it is in 3d

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [61]:
d = a.reshape((3,3,1,1,1,1,1))
d
# Now it is in 7d

array([[[[[[[0]]]]],




        [[[[[1]]]]],




        [[[[[2]]]]]],





       [[[[[[3]]]]],




        [[[[[4]]]]],




        [[[[[5]]]]]],





       [[[[[[6]]]]],




        [[[[[7]]]]],




        [[[[[8]]]]]]])

In [62]:
# What if we don't want to use reshape every time
# we will use two seperate fuunctions 1). np.expand_dims, 2). np.newaxis / None.

In [66]:
e = np.expand_dims(a,axis=0)
e.shape

# earlier a was 1d. Now it is 2d

(1, 9)

In [68]:
f = np.expand_dims(a,axis=1)
f.shape

(9, 1)

In [69]:
 # Some more examples

In [70]:
a = np.arange(1,13).reshape((3,4))
a.shape

(3, 4)

In [73]:
b = np.expand_dims(a,axis=1)
b.shape

# Think of axis as index. It will be easy for you to understand.

(3, 1, 4)

In [75]:
c=np.expand_dims(a,axis=2)
c.shape

(3, 4, 1)

In [76]:
# But what if want to create 1d to 4d/7d/100d directly.
# For that we will use our next function. np.newaxis / None

In [77]:
a.shape

(3, 4)

In [78]:
a[:,np.newaxis,:,np.newaxis].shape

(3, 1, 4, 1)

In [79]:
# Can create as many as we want
a[np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis,:,:].shape

(1, 1, 1, 1, 1, 1, 3, 4)

In [80]:
a[None,None,None,:,:].shape

(1, 1, 1, 3, 4)

# Reduction. 
## Reduces all the ones

In [82]:
# we will use squeeze function. It will remove all the ones.

a = np.arange(1,13).reshape((1,3,1,1,1,4,1))
a.shape

(1, 3, 1, 1, 1, 4, 1)

In [84]:
np.squeeze(a).shape

(3, 4)

# Stacking
\
## Spliting

In [88]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
# what if you want it to split in 3 equal parts

np.split(a,3)

# It will give you a list of 3 equal numpy sub arrays.

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [92]:
# We can do it many different ways.

np.split(a,[4,5])

# This is like slicing we will always go in right direction. first 0-4 (excluding 4) AND then 4 to 5(excluding 5) AND then 5 to end.

[array([1, 2, 3, 4]), array([5]), array([ 6,  7,  8,  9, 10, 11, 12])]

In [94]:
np.split(a,[4,5,5])

# IT will not give us an error, rather it will give us an empty subarray.

[array([1, 2, 3, 4]),
 array([5]),
 array([], dtype=int32),
 array([ 6,  7,  8,  9, 10, 11, 12])]

In [95]:
# We can also jumbled it like this. Still it will not give us any error.

In [96]:
np.split(a,[4,5,7,5])

[array([1, 2, 3, 4]),
 array([5]),
 array([6, 7]),
 array([], dtype=int32),
 array([ 6,  7,  8,  9, 10, 11, 12])]

In [97]:
np.split(a,[4,6,30])

[array([1, 2, 3, 4]),
 array([5, 6]),
 array([ 7,  8,  9, 10, 11, 12]),
 array([], dtype=int32)]

In [100]:
np.split(a,[-5,-2])

# It will work However it always goes in right direction

[array([1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10]), array([11, 12])]

In [101]:
# Now let's dive into 2d numpy arrays

In [102]:
a = np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
# By default axis = 0
# we are vertically dividing into 3 equal parts

np.split(a,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [105]:
np.split(a,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [107]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
np.split(a,[1],axis=0)

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])]

In [110]:
np.split(a,[2,3],axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]

In [111]:
# TO AVOID THE CONFUSION OF AXIS. WE HAVE TWO INBUILT FUNCTIONS IN NUMPY.
# 1). np.hsplit() , 2).np.vsplit()

In [112]:
np.vsplit(a,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [113]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

# Assignments

In [118]:
"""
Which of the following code will NOT throw an error ? 

A. 
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)
 
B.
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)
 
C.
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)
 
D.
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

"""

# Solution - None of these

'\nWhich of the following code will NOT throw an error ? \n\nA. \narr1 = np.array([1,2,3])\narr2 = np.array([9,8,7])\nnp.dot(arr1, arr2)\n \nB.\narr1 = np.array([[1,2], [3,4]])\narr2 = np.array([[1], [2]])\nnp.dot(arr1, arr2)\n \nC.\narr1 = np.array([1,2,3])\nk = 3\nnp.dot(arr1, k)\n \nD.\narr1 = np.array([[1,2], [3,4]])\narr2 = np.array([1,1])\nnp.dot(arr1, arr2)\n\n'

In [119]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [120]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [121]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [122]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [128]:

# What will be the outcome of the following code snippet ?


# x = np.ones((5,5))*[1:-1,1:-1] = 0

#solution should be some thing like this

#[[1. 1. 1. 1. 1.]
#[1. 0. 0. 0. 1.]
#[1. 0. 0. 0. 1.]
#[1. 0. 0. 0. 1.]
#[1. 1. 1. 1. 1.]]