# NPS Score of Airbnb 

In [5]:
!gdown 14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8

Downloading...
From: https://drive.google.com/uc?id=14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8
To: C:\Users\htc\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|##########| 2.55k/2.55k [00:00<?, ?B/s]


In [23]:
import numpy as np

score = np.loadtxt("C:/Users/htc/survey.txt",dtype = 'int')

In [24]:
# Now I have a Numpy array (score) which is nothing but customer's rating.
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [25]:
# Total customers. we have to fetch this out from the tuple. we will do it later. first let's analyse some basic stuff.
score.shape

(1167,)

In [26]:
# Minimum rating customers gave us. Thankfully It is not 0 LOl.
score.min()

1

In [27]:
# Maximum rating I've got from customers. 
score.max()

10

In [28]:
# NPS = %PROMOTERS - % DETRACTORS. Let's calculate both one by one.
# Detractors - we are choosing those customers who gave us rating below and equal to 6 as our detractors.

In [55]:
Detractors = score[score<=6]

In [56]:
Detractors_numbers = Detractors.shape[0]
print(Detractors_numbers)

332


In [46]:
# Calculating Detractors Percentage Here.

Total_customers = score.shape[0]

Percentage_Detractors = (Detractors_numbers/Total_customers)*100

print(Percentage_Detractors)

28.449014567266495


In [47]:
# Now We Will Calculate Promoters Percentage.
# AS a Data Scientist be more responsible and make the code shorter.

In [50]:
Promoters = score[score>=9].shape[0]
print(Promoters)

609


In [51]:
# Now calculating Promoters percentage here
Percentage_Promoters = (Promoters/Total_customers)*100
print(Percentage_Promoters)

52.185089974293064


In [54]:
# Finally Let's Calculate Net Promoter Score.

NPS = Percentage_Promoters - Percentage_Detractors
print(NPS)

# Just Like this If we Calculate the NPS every month/quarter/year. We can Analyse our customers sentiments.
# If our customer sentments are changing in positive direction or not.

23.73607540702657


# Practice

In [58]:
# Numpy allows us to assign value like this . Broadcasting we call it.
a = np.array([0,1,2,3,4,5])
a[4:]=10
a

array([ 0,  1,  2,  3, 10, 10])

In [62]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.ndim,a.shape

(1, (9,))

In [65]:
a = np.arange(12)
a[:5] = 23
a

array([23, 23, 23, 23, 23,  5,  6,  7,  8,  9, 10, 11])

In [66]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8])
a[2:] = b[::-1]
a

array([1, 2, 8, 7, 6])

In [68]:
# Masking Indexing/Fancy Indexing
# It is so fast and we don't need to use any for loop or anything.

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
mask = a<6
print(mask)

[ True  True  True  True  True  True False False False False False False]


In [71]:
a[mask]

array([0, 1, 2, 3, 4, 5])

In [72]:
# Or do it easy way
a[a<6]

array([0, 1, 2, 3, 4, 5])

In [75]:
# Now let's work with two conditions
# First we will make it lengthy. Just to elaborate it better.
# Then we will just write it in a way data scientists write.

a = np.arange(20)

# we need to fetch the elements that is either divisible by 2 or divisible by 5.

mask1 = a%2==0
mask2 = a%5==0

a[mask1 | mask2]

array([ 0,  2,  4,  5,  6,  8, 10, 12, 14, 15, 16, 18])

In [76]:
# Let's do it in one line only

a[(a%2==0) | (a%5==0)]

array([ 0,  2,  4,  5,  6,  8, 10, 12, 14, 15, 16, 18])

In [77]:
# Quiz
a = np.array([0,1,2,3,4,5])
mask = (a%2==0)
a[mask] = -1

a

array([-1,  1, -1,  3, -1,  5])

In [78]:
a = np.arange(4)
a+3
a

array([0, 1, 2, 3])

In [79]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [80]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [81]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a/b

array([0.25, 0.4 , 0.5 ])

In [82]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a-b

array([-3, -3, -3])

In [83]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a>b

array([False, False, False])

In [84]:
a = np.array([0,1,2,3])
np.sum(a)

# This implementation is done inside numpy library

6

In [85]:
a.sum()

# This implementation is done in numpy.ndarray

6

In [86]:
np.mean(a)

1.5

In [87]:
a.mean()

1.5

In [88]:
np.min(a)

0

In [89]:
a.min()

0

In [90]:
np.max(a)

3

In [91]:
a.max()

3