# Practice

In [45]:
# Why do we use Numpy? Normal Python vs Numpy
# Normal python example

a=[1,2,3,4,5]
l= []
for i in a:
    l.append(i**2)
print(l)

# So many Lines of codes

[1, 4, 9, 16, 25]


In [12]:
# Here is an example of numpy arrays

import numpy as np
r = np.array([1,2,3,4,5])
r**2

# Just import numpy, create a numpy array & boom we don't have to write so many lines of codes.
# Numpy arrays are better than python lists in terms of speed. Numpy arrays are much more efficient & Optimised.
# Numpy arrays are inherently using C lang. arrays. Because Numpy library is written in C language.

array([ 1,  4,  9, 16, 25])

In [14]:
# Proof numpy is faster than Python
# Here is an example of python. we will time it both python and numpy one by one.

l = range(10)
%timeit [i**2 for i in l]

# output in micro seconds


1.18 µs ± 61.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
# now numpy

R = np.array(range(10))
%timeit R**2

# output in nano seconds


873 ns ± 33.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
# Python lists are heterogeneous, we can store multiple datatypes.

k = [1,2,3,1.1,2.2,3.3,'r','k','R',True,False]
k

[1, 2, 3, 1.1, 2.2, 3.3, 'r', 'k', 'R', True, False]

In [19]:
# Numpy arrays are homogeneous. Let's see some examples to understand how numpy array behaves.
 
a = np.array([1,2,3,4,5,6.5])
a

# It reads int,int,int,int,int and then Float. Now  I cannot adjust Float in the memory of integers.
# So it automatically converted all the elements into floats(Higher Values)

array([1. , 2. , 3. , 4. , 5. , 6.5])

In [20]:
# Let's see some more examples with other datatypes.

b = np.array([1,2,3,4,5,'numpy','python'])
b

array(['1', '2', '3', '4', '5', 'numpy', 'python'], dtype='<U11')

In [23]:
c = np.array([1,2,3,4,True,False])
c

# 1 for True , 0 for False

array([1, 2, 3, 4, 1, 0])

In [25]:
# Dimensions in numpy 
# some attributes in numpy ndim,shape,arange

a = np.array([1,2,3,4,5])
a.ndim

# tells us the dimension of numpy array

1

In [28]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b
b.ndim

2

In [30]:
# shape attribute tells us, How many values I have in each dimension

a = np.array([1,2,3,4])
a
a.shape

(4,)

In [33]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b
b.shape

(4, 3)

In [34]:
# types in numpy arrays

type(a)

# tells us that the identifier a. It's entirety in numpy n dimensional array(where n can be any no.).

numpy.ndarray

In [35]:
# dtype in numpy arrays

a.dtype

# tells us the datatype of value stored in the numpy array

dtype('int32')

In [36]:
# arange function in numpy

l = np.arange(10)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# How arange differs from range function.
# arange allows us to assign stepsize in float as well. And that's not the case in range function

l = np.arange(1,5,.5)
l

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [39]:
# Special method in numpy that allows us to access multiple indices at the same time.

a = np.array([1,2,3,7,8,9,4,5,6])
a[[4,5]]

array([8, 9])

In [40]:
# Slicing in numpy arrays
a = np.array([1,2,3,4,5,6])
a[:4]

array([1, 2, 3, 4])

In [42]:
b = np.array([2,3,4,5,6])
b[::-1]

array([6, 5, 4, 3, 2])

In [43]:
b[:-3:-1]

array([6, 5])

In [44]:
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
c[-5:-2:-1]
# empty array

array([], dtype=int32)

# Assignments

In [47]:
# Add 1 to each elements

A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])
A+1

array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6])

In [49]:
#Create a sequence of a given length from a given start point, where the difference between 2 consecutive elements of the expected sequence is also given as step.
#Input Format:
#One line of input will have 3 space-separated integers consisting of start, length of sequence and step between two continuous elements of the sequence.
#Output Format:
#numpy array of integers

b = np.arange(5,35,3)
b

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [51]:
#Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

c = np.arange(22,71,2)
c

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [52]:
# Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

d = np.arange(21,72,2)
d

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [67]:
# Given a 1D array, return the first and last elements from the array.

e = np.array([0,1,2,3,4,5])

def first_last_element(e):
    first_element = e[0]
    last_element = e[-1]
    return (first_element,last_element)

first_last_element(e)


(0, 5)

In [59]:
#Given an array, return the shape and dimension of the array.

f = np.array([1,2,3,4,5])
f.shape,f.ndim

((5,), 1)

In [60]:
# Given the start, end, and the stepsize return a numpy array sequence in given range with the specified stepsize.

g = np.arange(5,7,0.5)
g

array([5. , 5.5, 6. , 6.5])

In [70]:
#Given an array of marks, return the array only containing elements with marks > 40

h = np.array([85, 18, 2, 57, 65, 44])
def filtering_marks(h):
    return h[h>40]

filtering_marks(h)

array([85, 57, 65, 44])

In [71]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

# Let's go through the process 
# first (x >= -5) we will get this ([True,True,True,True,True,True,True,True,False]),
# second (x<=15) we will get this ([True,True,False,False,True,True,False,True,True])
# Combine first & second = ([True,True,False,False,True,True,False,True,False])
# After this we are multiplying it with -1

[  5  -9  20  25   3  -5  16 -10  -8]
