# Practice

In [11]:
# empty function in numpy. How empty function behaves?
# This will create a 1d array,2d arrays etc. However the value it will assign inside the array will be very small and easily  replacable.
import numpy as np
a = np.empty(10)
a

array([6.95216015e-310, 6.95216015e-310, 2.17374124e+068, 2.28176405e+243,
       2.46818041e-154, 1.89305828e+219, 1.43397140e+166, 6.05979519e+233,
       2.34896698e+251, 2.90469054e+180])

In [13]:
a = np.empty((3,4))
a

array([[9.78077283e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.54668033e+185, 5.45740224e-066,
        9.16226847e-072],
       [6.53454595e-042, 1.60306899e-051, 1.36318062e+161,
        9.34601771e-067]])

In [19]:
# Unique function. How unique function behaves in numpy
# This function remove duplicates just like set. And there is a special parameter, we can provide in this function to actually know the frequency of the element.

a = np.array([1,2,3,4,5,1,2,3,4,5,1,2,3,1,2,3,1,3,6,4,7,9,7,9,9])
np.unique(a,return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7, 9]), array([5, 4, 5, 3, 2, 1, 2, 3], dtype=int64))

### 2D Matrices

In [22]:
a = np.array([[1,2,3]])

a.shape

(1, 3)

In [29]:
a = np.array([[1,2,3],[4,5,6]])
a
a.shape


(2, 3)

In [30]:
a = np.array([0,4,5])
b = np.array([1,3,5])
a>=b

array([False,  True,  True])

In [31]:
a = np.array([0,1,2,3,4,5])
mask = (a%2==0)
a[mask]= -1
a

array([-1,  1, -1,  3, -1,  5])

In [37]:
# Using reshape function, we can create our matrix by using some set of factors.
a = np.arange(1,13)
a.reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [40]:
a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
# Transpose
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
d = np.arange(1,25).reshape((4,6))
d.T

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [52]:
# How do we change any matrix back to Vector?
t = np.arange(1,13).reshape((3,4))
t
t.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Indexing and Slicing on 2d

In [55]:
t=np.arange(1,13).reshape(3,4)
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
# fetching first row
t[0]

array([1, 2, 3, 4])

In [57]:
# try to fetch first index of 0th row.
t[0][1]
# Although it is giving us the answer. It is not a good practice to use it.

2

In [58]:
# An easy way

t[0,1]

2

In [59]:
# try to fetch 11 using negative indexing

t[-1,-2]

11

In [60]:
# Now try to fetch multiple elements in one go (let's say these 6,4,12)
# Logic is to put rows in first[[rows],[cols]].
# Because in the backend numpy will do it bitwise.

t[[1,0,2],[1,3,3]]

array([ 6,  4, 12])

In [61]:
# try to fetch 5,7,10,8

t[[1,1,2,1],[0,2,1,3]]

array([ 5,  7, 10,  8])

## Slicing

In [62]:
t = np.arange(1,13).reshape(3,4)
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
# try to fetch this segment([[1,2,3],[5,6,7]])

t[:2 , :3]

array([[1, 2, 3],
       [5, 6, 7]])

In [67]:
# let's try to fetch a complex slice. fetch 1,3,9,11

t[::2 , ::2 ]

array([[ 1,  3],
       [ 9, 11]])

In [68]:
t[::,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [69]:
t[:: , 1:3:2]

array([[ 2],
       [ 6],
       [10]])

### Negative Indexing

In [74]:
# Logic behind this, first it will reverse all the rows and then reverse the cols with the resultant matrix.
t[::-1,::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [73]:
# Quiz
t[::-1,::-2]

array([[12, 10],
       [ 8,  6],
       [ 4,  2]])

In [75]:
# Quiz
t[::-2,::-2]

array([[12, 10],
       [ 4,  2]])

# Assignments

In [77]:
#Given a M x N array, Perform the following operations:1. Get the odd rows from the array i.e. 1st, 3rd, 5th etc..2. Convert the above result into 1D array and return it.

a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
# Getting the odd rows from this matrix.
b = a[1::2]
b

array([[4, 5, 6]])

In [84]:
# Now converting this matrix back to vector.

c = b.flatten()
c

array([4, 5, 6])

In [ ]:
""" Given a 2d array, write a program to return a subarray such that the subarray consists of the elements from:

1. the second to the fourth row of the original array,

2. the elements in these rows should be from the last three columns of the corresponding rows of the original array,

3. the rows should be in reversed order.
"""

In [85]:
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11],[12, 13, 14, 15],[16, 17, 18, 19]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [91]:
# Let's go stepwise

b = a[1:4,1:]
b

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [92]:
# now reversing the rows
b[::-1]

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])

In [93]:
X = np.arange(12).reshape(3,4)
X


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
#Given a 2D numpy array, return array with its values in the column reversed.
#rotate the matrix clockwise by 90º.

a = np.array([[1, 2, 3], 
 [4, 5, 6],
 [7, 8, 9]])
a,

[[7 4 1]
 [8 5 2]
 [9 6 3]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
b = a.T
b[::,::-1]

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])