In [1]:
# USE CASE : FITNESS DATA ANALYSIS OF A PERSON 
# LOADING DATA SET AND EDA USING NUMPY

In [2]:
import numpy as np

In [44]:
!gdown 1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: C:\Users\htc\fit.txt

  0%|          | 0.00/3.43k [00:00<?, ?B/s]
100%|##########| 3.43k/3.43k [00:00<?, ?B/s]


In [46]:
data = np.loadtxt("C:/Users/htc/fit.txt",dtype='str')

In [48]:
# Since the data has many rows. we are just fetching top 5 rows for now. To check the granularity of the data
# Data is homogeneous.
# we might do type casting later
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [49]:
# A total of 96 Datapoints and 6 Features we have in our fitness data
data.shape

(96, 6)

In [50]:
# WE ARE TRYING TO FETCH DETAILS OF EACH COLUMN IN A SEPERATE IDENTIFIER. SO IT WILL BE EASY FOR US TO WORK WITH THE DATA.
# WE WILL DO IT SIMPLY BY PERFORMING A TRANSPOSE FUNCTION.

In [51]:
date,steps_count,mood,calories_burned,hours_of_sleep,activity_status = data.T

In [59]:
# some of our columns are in string format but they need to be in int format.
# columns like steps_count,calories_burned,hours_of_sleep

steps_count = np.array(steps_count,dtype='int')

calories_burned = np.array(calories_burned, dtype='int')

hours_of_sleep = np.array(hours_of_sleep,dtype='int')

In [61]:
# we are checking up on his mood. How does he feel most of the times?
# He has 3 moods, either he is happy,neutral or sad.

np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [63]:
# Now we are checking on Average how much steps he walk.

avg_steps_count = np.mean(steps_count)

In [64]:
avg_steps_count 

2935.9375

In [69]:
# On which day he took the maximum steps.
print(np.max(steps_count))
print(date[np.argmax(steps_count)])

7422
14-12-2017


In [70]:
# On which day he took the minimum steps.

print(np.min(steps_count))
print(date[np.argmax(steps_count)])

25
14-12-2017


In [73]:
# Day on which he burned the maximum no. of calories.

print(np.max(calories_burned))
print(date[np.argmax(calories_burned)])

243
14-12-2017


In [ ]:
# Let's try to correlate his mood with the counts of steps he is taking.
# Let's find the Avg. stepscount on those days where his mood was Sad

In [81]:
avg_steps_mood_sad = np.mean(steps_count[mood=='Sad'])

In [82]:
# His Average stepscount is greater than his average stepscount when he is sad.
# Can we draw this insight from here that when his mood was sad. he is more likely to walk less.

print(avg_steps_count)
print(avg_steps_mood_sad)

2935.9375
2103.0689655172414


In [87]:
# Let's correlate this same situation with when his mood was happy.

avg_steps_mood_happy = np.mean(steps_count[mood=='Happy'])

In [88]:
# His Average stepscount is smaller than his average stepscount when he is happy.
# Can we draw this insight from here that when his mood was happy. he is more likely to walk more.

print(avg_steps_count)
print(avg_steps_mood_happy)

2935.9375
3392.725


In [90]:
# find if he is taking more than 4000 steps. how was his mood and frequency.

np.unique(mood[steps_count>4000],return_counts =  True)

# This is clear when is taking more than 4k steps a day then his mood was happy most of the time

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

In [92]:
# find if he is sleeping for more than 4 hours. how was his mood and frequency.

np.unique(mood[hours_of_sleep>4],return_counts =  True)

# When he is sleeping for more than 4 hours. his mood was happy most of the time.

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([33, 18, 19], dtype=int64))

In [93]:
# Final insights. 
# He should walk atleast 4000 steps every day and have a sound sleep of more than 4 hours. If he do this, he has great chance that his mood will be happt.

# Practice

In [ ]:
# SORTING FUNCTIONS ON 2D ARRAYS

In [4]:
# Simple sorting on 1d array.
a = np.array([5,4,2,6,9,4,5,1,2,6,4,4])
np.sort(a)

array([1, 2, 2, 4, 4, 4, 4, 5, 5, 6, 6, 9])

In [25]:
# now sorting on 2d arrays.
# by default axis =-1
b = np.array([[5,8,2,7],[9,5,8,0],[7,2,8,1],[2,6,20,30]])
b

array([[ 5,  8,  2,  7],
       [ 9,  5,  8,  0],
       [ 7,  2,  8,  1],
       [ 2,  6, 20, 30]])

In [26]:
# sorting in vertical direction.
np.sort(b,axis=0)

array([[ 2,  2,  2,  0],
       [ 5,  5,  8,  1],
       [ 7,  6,  8,  7],
       [ 9,  8, 20, 30]])

In [27]:
# sorting in horizontal direction.
np.sort(b,axis=1)

array([[ 2,  5,  7,  8],
       [ 0,  5,  8,  9],
       [ 1,  2,  7,  8],
       [ 2,  6, 20, 30]])

In [28]:
# negative axis -1 is same as axis = 1 in 2d np.arrays.

np.sort(b,axis=-1)

array([[ 2,  5,  7,  8],
       [ 0,  5,  8,  9],
       [ 1,  2,  7,  8],
       [ 2,  6, 20, 30]])

In [29]:
# negative axis -2 is same as axis = 0 in 2d np.arrays.
np.sort(b,axis=-2)

array([[ 2,  2,  2,  0],
       [ 5,  5,  8,  1],
       [ 7,  6,  8,  7],
       [ 9,  8, 20, 30]])

In [30]:
# argsort function.
# arg sort function returns us the indices that would sort an array

In [31]:
# simple 1d array
a = np.array([7,8,9,4,5,6,1,2,3])
np.argsort(a)

array([6, 7, 8, 3, 4, 5, 0, 1, 2], dtype=int64)

In [32]:
# Also we can find the index of the maximum value in the np.array
# using argmax function

np.argmax(a)

2

In [33]:
# Also we can find the index of the minimum value in the np.array
# using argmin function

np.argmin(a)

6

In [34]:
# let's take some examples of 2d arrays
# argsort vertically

np.argsort(b,axis=0)

array([[3, 2, 0, 1],
       [0, 1, 1, 2],
       [2, 3, 2, 0],
       [1, 0, 3, 3]], dtype=int64)

In [36]:
#argsort horizontally

np.argsort(b,axis=1)

array([[2, 0, 3, 1],
       [3, 1, 2, 0],
       [3, 1, 0, 2],
       [0, 1, 2, 3]], dtype=int64)

In [37]:
# argmax vertically

np.argmax(b,axis=0)

array([1, 0, 3, 3], dtype=int64)

In [38]:
# argmax horizontally

np.argmax(b,axis=1)

array([1, 0, 2, 3], dtype=int64)

In [39]:
# Since there is no default axis, It flattened the entire array and then give the index of maximum element.

np.argmax(b)

15

In [40]:
# Let's work with argmin
# First Vertically

np.argmin(b,axis=0)

array([3, 2, 0, 1], dtype=int64)

In [41]:
# Horizontally

np.argmin(b,axis=1)

array([2, 3, 3, 0], dtype=int64)

In [42]:
np.argmin(b)

7

## Reshaping using -ve index

In [4]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
# Here i'm telling numpy. I don't know how many rows you will create
a.reshape(-1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])